# roles/serveur/handlers/main.yml
---
- name: Start Apache
  service:
    name: apache2
    state: started
    enabled: true

- name: Restart Apache
  service:
    name: apache2
    state: restarted

